export const RECEIVE_RAWMESSAGES = 'RECEIVE_RAWMESSAGES';
export const RECEIVE_THREADS = 'RECEIVE_THREADS';
export const RECEIVE_ORDERED_THREADS = 'RECEIVE_ORDERED_THREADS';
export const RECEIVE_ALL_MESSAGES = 'RECEIVE_ALL_MESSAGES';
export const RECEIVE_THREAD_MESSAGES = 'RECEIVE_THREAD_MESSAGES';
export const RECEIVE_CURRENTID = 'RECEIVE_CURRENTID';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const GET_CURRENTID = 'GET_CURRENTID';